DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - SPELL_CSPELL
  - SPELL_LYCHEE
  - YAML_YAMLLINT
  - JSON_JSONLINT
  - REPOSITORY_TRIVY
  - SQL_TSQLLINT
  - CSHARP_ROSLYNATOR

EXCLUDED_DIRECTORIES:
  - frontend

CSHARP_DOTNET_FORMAT_ARGUMENTS:
  - "backend/backend.sln"
