#!/bin/sh

echo "
╔═══════════════════════════════════╗
║      RUNNING UNIT TESTS           ║
╚═══════════════════════════════════╝
"

npm run unit-test

echo "
╔═══════════════════════════════════╗
║   RUNNING INTEGRATION TESTS       ║
╚═══════════════════════════════════╝
"

npm run integration-test
