name: End-to-End Tests

on:
  workflow_call:

jobs:

  playwright:
    name: "Playwright E2E Tests"
    runs-on: ubuntu-latest
    environment: secrets
    env:
      BASEURL: ${{ secrets.BASEURL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"

      - name: Build
        working-directory: e2e_playwrighttests
        run: dotnet build 
      
      - name: Ensure browsers are installed
        working-directory: e2e_playwrighttests/PlaywrightTests
        run: pwsh bin/Debug/net9.0/playwright.ps1 install --with-deps

      - name: Run Playwright Tests
        working-directory: e2e_playwrighttests
        run: dotnet test
