name: End-to-End Tests

on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      BASEURL: ${{ secrets.BASEURL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"

      - name: Build & Install
        run: dotnet Build

      - name: Install Playwright Browsers
        run: pwsh bin/Debug/net9.0/playwright.ps1 install

      - name: Run Playwright Tests
        run: dotnet test e2e_playwrighttests/playwright.sln --filter TestCategory=E2ETest
