name: Integration DB Test
on:
    push:
        branches: [feat/get-adress-ci]
        paths:
            - backend/api/Repositories/**
            - backend/api/Services/**
            - backend/api/DBContext/**
            - backend/api/Migrations/**
            - backend/getAddressTest/IntegrationTest/**

jobs:
    IntegrationDbTest:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:latest
                env:
                    POSTGRES_DB: getaddressdb
                    POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
                    POSTGRES_USER: ${{secrets.POSTGRES_USER}}
                    POSTGRES_HOST_AUTH_METHOD: trust
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd="pg_isready -U testuser"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=5
        env:
            ConnectionStrings__Default: ${{secrets.CONNECTIONSTRINGS__DEFAULT}}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Cache NuGet packages
              uses: actions/cache@v4
              with:
                  path: ~/.nuget/packages
                  key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-nuget-
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "9.0.x"
            - name: Restore dependencies
              run: dotnet restore backend/getAddressTest/getAddressTest.csproj
            - name: Build
              run: dotnet build backend/getAddressTest/getAddressTest.csproj  --filter "TestCategory!=UnitTest" --no-restore --configuration Release
