name: Pull Request

on:
  pull_request:

jobs:
  unit-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/UnitTest.yml
  integration-db-tests:
    name: Run Integration DB Tests
    uses: ./.github/workflows/IntegrationDbTest.yml
