name: Pull Request

on:
  pull_request:

jobs:
  unit-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/unit_test.yml

  integration-tests:
    name: Run Integration Tests
    needs: unit-tests
    uses: ./.github/workflows/integration_test.yml
