name: Merge to Main

on:
  push:
    branches:
      - main

jobs:
  call-tests:
    name: Run Unit and Integration Tests in Backend
    uses: ./.github/workflows/unit_and_integration_test.yml

  deploy-containers:
    name: Deploy application to VM
    runs-on: ubuntu-latest
    needs: call-tests
    environment: secrets
    steps:
      - uses: actions/checkout@v4

      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@v1.2.2
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PW: ${{ secrets.POSTGRES_PASSWORD }}
        with:
          host: ${{ vars.VM_IP_ADDRESS }}
          username: ${{ vars.VM_USER }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          envs: POSTGRES_USER,POSTGRES_PW
          script: |
            echo "cd to working directory"
            cd ./deployment
            
            echo "Delete old repository"
            rm -rf man-sign-1

            echo "Clone repository"
            git clone https://github.com/${{ github.repository }}.git

            echo "cd to repository"
            cd man-sign-1

            echo "Ensure Docker is installed"
            docker --version

            echo "Remove existing containers"
            sudo docker compose down

            echo "Delete all local images"
            sudo docker image prune --all --force

            echo "Insert variables for building containers"
            echo "POSTGRES_USER=$POSTGRES_USER" > .env
            echo "POSTGRES_PW=$POSTGRES_PW" >> .env

            echo "Build containers"
            sudo docker compose --env-file .env up -d
