name: Merge to Main

on:
  push:
    branches:
      - main

jobs:
  call-tests:
    name: Run Unit and Integration Tests in Backend
    uses: ./.github/workflows/unit_and_integration_test.yml

  automated-api-tests:
    name: API testing with Postman CLI
    needs: deploy-containers
    runs-on: ubuntu-latest
    environment: secrets
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "48703513-b9040924-18c2-450d-b42c-ebcd117e744d" -e "48703513-f48ae237-b84f-455d-a07c-df1eab3b6852"
